version: '3.1'

services:
  app:
    container_name: climate-map-app
    build: .
    env_file:
      - ./.env.example
      - ./.env
    ports:
      - "${DEV_PORT}:3000"
    volumes:
        - .:/app:z
