version: '3.1'

services:
  app:
    container_name: climate-map-app
    build: .
    restart: always
    env_file:
      - ./default.env
      - ./.env
    ports:
      - "${DEV_PORT}:3000"
    volumes:
        - .:/app:z
        - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
