version: '3.1'

services:
  app:
    container_name: climate-map-app
    build: .
    restart: always
    env_file:
      - ./default.env
      - ./.env
    ports:
      - "${DEV_PORT}:3000"
    volumes:
        - .:/app:z
