export const SIDEBAR_CLOSED_WIDTH = 64

export const SIDEBAR_PADDING_REM = 2

export const SCROLLBAR_WIDTH_REM = 0.75

export const SIDEBAR_PADDING_WITH_SCROLLBAR_REM =
  SIDEBAR_PADDING_REM + SCROLLBAR_WIDTH_REM
